### ISSUE TITLE
Doesn't handle lists

### ISSUE THREAD

**Issue by AntoineAugusti** [entrepreneur-interet-general/open_api_schemas_to_markdown#1]
```yaml
components:
  schemas:
    Operation:
      properties:
        operation_id:
          type: integer
          format: int64
          description: Le numéro unique de l'opération
          example: 1119920371
        pourquoi_alerte:
          type: string
          enum: [SAR, MAS, DIV, SUR]
          description: >
            La catégorie du type d'intervention.
              - SAR (search and rescue) : vie humaine en danger.
              - MAS (maritime assistance service) : assistance aux navires
              - SUR : sûreté des navires
              - DIV : autres cas
          example: SAR
```

Will not produce a valid Markdown file
